//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEMICAL_ELEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHEMICAL_ELEMENT()
        {
            this.SPEKTR = new HashSet<SPEKTR>();
        }
    
        public int id_element { get; set; }
        public string element_name { get; set; }
        public Nullable<int> atomic_number { get; set; }
        public Nullable<double> atomic_weight { get; set; }
        public string description { get; set; }
        public Nullable<int> core { get; set; }
        public Nullable<int> ions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPEKTR> SPEKTR { get; set; }
    }
}
