//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITY()
        {
            this.POSITION = new HashSet<POSITION>();
        }
    
        public int kod_country { get; set; }
        public int kod_location { get; set; }
        public int kod_city { get; set; }
        public string city_name { get; set; }
        public string administrative_devision { get; set; }
        public string region { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POSITION> POSITION { get; set; }
    }
}
