//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREATION_DATE
    {
        public int kod_date { get; set; }
        public Nullable<System.DateTime> date_value { get; set; }
    
        public virtual DATE_REMARKS DATE_REMARKS { get; set; }
    }
}
