//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaserExpertiseContextEntities1 : DbContext
    {
        public LaserExpertiseContextEntities1()
            : base("name=LaserExpertiseContextEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ARTWORK> ARTWORK { get; set; }
        public virtual DbSet<ARTWORK_GENRE> ARTWORK_GENRE { get; set; }
        public virtual DbSet<ARTWORK_TYPE_POSITION> ARTWORK_TYPE_POSITION { get; set; }
        public virtual DbSet<AUTHOR> AUTHOR { get; set; }
        public virtual DbSet<CHEMICAL_ELEMENT> CHEMICAL_ELEMENT { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<CREATION_DATE> CREATION_DATE { get; set; }
        public virtual DbSet<EPOCH> EPOCH { get; set; }
        public virtual DbSet<FOCUS_SECTION_SpectralResearch_> FOCUS_SECTION_SpectralResearch_ { get; set; }
        public virtual DbSet<FOTO> FOTO { get; set; }
        public virtual DbSet<HISTORICAL_PERIOD> HISTORICAL_PERIOD { get; set; }
        public virtual DbSet<INSTRUMENTAL_METHODS> INSTRUMENTAL_METHODS { get; set; }
        public virtual DbSet<LIBRARY_OF_SPEKTR_LINES> LIBRARY_OF_SPEKTR_LINES { get; set; }
        public virtual DbSet<LOCATION> LOCATION { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<PAINTING_SCHOOL> PAINTING_SCHOOL { get; set; }
        public virtual DbSet<PAINTING_STYLE> PAINTING_STYLE { get; set; }
        public virtual DbSet<PAINTING_TECHNIQUE> PAINTING_TECHNIQUE { get; set; }
        public virtual DbSet<PAINTS> PAINTS { get; set; }
        public virtual DbSet<PIGMENTS> PIGMENTS { get; set; }
        public virtual DbSet<POSITION> POSITION { get; set; }
        public virtual DbSet<Privileges> Privileges { get; set; }
        public virtual DbSet<SPEKTR> SPEKTR { get; set; }
        public virtual DbSet<SPEKTR_LINE> SPEKTR_LINE { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<DATE_REMARKS> DATE_REMARKS { get; set; }
        public virtual DbSet<PASSPORT_RESEARCH> PASSPORT_RESEARCH { get; set; }
    }
}
