//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOCUS_SECTION_SpectralResearch_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOCUS_SECTION_SpectralResearch_()
        {
            this.SPEKTR = new HashSet<SPEKTR>();
        }
    
        public int id_focus { get; set; }
        public Nullable<int> kod_artwork { get; set; }
        public string focus_name { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public byte[] file { get; set; }
        public string PointFocusDescription { get; set; }
        public string MainColourFocus { get; set; }
    
        public virtual ARTWORK ARTWORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPEKTR> SPEKTR { get; set; }
    }
}
