//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOTO
    {
        public int kod_foto { get; set; }
        public Nullable<int> kod_artwork { get; set; }
        public string path_to_foto { get; set; }
        public byte[] foto_notes { get; set; }
    
        public virtual ARTWORK ARTWORK { get; set; }
    }
}
