//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICAL_PERIOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISTORICAL_PERIOD()
        {
            this.ARTWORK = new HashSet<ARTWORK>();
        }
    
        public int kod_perioda { get; set; }
        public Nullable<int> kod_epoch { get; set; }
        public string period_name { get; set; }
        public byte[] short_description { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTWORK> ARTWORK { get; set; }
        public virtual EPOCH EPOCH { get; set; }
    }
}
