//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARY_OF_SPEKTR_LINES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRARY_OF_SPEKTR_LINES()
        {
            this.SPEKTR_LINE = new HashSet<SPEKTR_LINE>();
        }
    
        public byte id_library { get; set; }
        public string name_library { get; set; }
        public string library_description { get; set; }
        public string comments_library { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPEKTR_LINE> SPEKTR_LINE { get; set; }
    }
}
