//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSPORT_RESEARCH
    {
        public Nullable<int> kod_artwork { get; set; }
        public int kod_method { get; set; }
        public string conclusion_method { get; set; }
    
        public virtual ARTWORK ARTWORK { get; set; }
        public virtual INSTRUMENTAL_METHODS INSTRUMENTAL_METHODS { get; set; }
    }
}
