//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIGMENTS
    {
        public int id_pigment { get; set; }
        public int kod_paint { get; set; }
        public string pigment_name { get; set; }
        public string pigment_group { get; set; }
        public string pigment_description { get; set; }
    
        public virtual PAINTS PAINTS { get; set; }
    }
}
