//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEKTR_LINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPEKTR_LINE()
        {
            this.SPEKTR = new HashSet<SPEKTR>();
        }
    
        public long id_sp_line { get; set; }
        public byte id_library { get; set; }
        public Nullable<System.DateTime> Date_line { get; set; }
        public string Name_of_the_person { get; set; }
        public Nullable<double> WavellengthLine { get; set; }
        public string Other_options { get; set; }
    
        public virtual LIBRARY_OF_SPEKTR_LINES LIBRARY_OF_SPEKTR_LINES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPEKTR> SPEKTR { get; set; }
    }
}
