//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserExpertise.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEKTR
    {
        public int kod_spektr { get; set; }
        public int id_focus { get; set; }
        public long id_sp_line { get; set; }
        public int id_element { get; set; }
        public Nullable<int> Wave_Length { get; set; }
        public string Line_Description { get; set; }
        public string Spektrs_Base { get; set; }
    
        public virtual CHEMICAL_ELEMENT CHEMICAL_ELEMENT { get; set; }
        public virtual FOCUS_SECTION_SpectralResearch_ FOCUS_SECTION_SpectralResearch_ { get; set; }
        public virtual SPEKTR_LINE SPEKTR_LINE { get; set; }
    }
}
